root_key = "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKSG3p1Wt0MFSiS5adWeXDlJuUONA7OKDXwlwNKMuvmYNfe/p/Cai44ErLpOo4mHLCLu+MVtn9bvekC/LnBgays="

db_path = "/tmp/db"

origin = "http://localhost:8080"

[email]
sender_email = "noa@resare.com"
relay_host = "mail.resare.com"

[persistence]
uri = "ws://localhost:8000/"
username = "idelephant"
password_file = "/tmp/password"
