root_key = "zq.luDCkyil5qf1qCJwm5lnSe97x5mROvXUMfwpOASJ0MgalZTIj"

db_path = "/tmp/db"

origin = "http://localhost:8080"

[email]
sender_email = "noa@resare.com"
relay_host = "mail.resare.com"

[persistence]
uri = "ws://localhost:8000/"
username = "idelephant"
password_file = "/tmp/password"

# Alternative auth via idmouse:
#[persistence.idmouse]
#url = "http://localhost:9000/token"
#bearer_token_file = "/tmp/idmouse-bearer-token"
