[[website]]
name = "id.noa.re"
namespace = "idelephant"
replicas = 1
args = ["-c", "/config/idelephant.toml"]
custom-token-audiences = ["idmouse"]
external-secrets = [
    "/email-password",
]
config = {"/config/idelephant.toml"="idelephant.toml"}

